### PR TITLE
ConfRoom API / Server Backend

### PR DESCRIPTION
**Pull request by davidsavagejr**
This adds an API project for more complex stuff in the future.
Updates ConfMe to use it - just temp hosted for now on Azure

Result is that conf rooms are saved permanently

### CODE REVIEW

**Comment by ajepst** [comment]
Wow... Interesting. My take: being not directly tied to the other hsbot stuff and a different language, this stuff feels like it should stand on its own in a separate repo. The changes to the coffee files would certainly stay here, however.

**Comment by davidsavagejr** [comment]
Good idea.  I'll move that stuff over to a new repo.

**Comment by davidsavagejr** [comment]
Looks like I don't have permission to create on.  @ChrisMissal / @ajepst - would be happy to move the server stuff to a new one once we have a home for it

**Comment by ajepst** [comment]
If you create it on your own github acct, we should be able to easily pull
it over to the HeadspringLabs account.

**Comment by davidsavagejr** [comment]
@ajepst should be all set now with minimal changes to hsbot.
new repo is here: https://github.com/davidsavagejr/hsbot.server

**Comment by pedroreys** [comment]
@davidsavagejr added you to the owners group of HeadspringLabs. you should be able to transfer the hsbot.server repo to the organization now.

**Comment by pedroreys** [comment]
@ajepst @ChrisMissal can we merge and close this PR now?

**Comment by ajepst** [comment]
Fine with me.

**Comment by ChrisMissal** [comment]
Server code lives here now: https://github.com/HeadspringLabs/hsbot.server

@davidsavagejr can I be a pain and ask you to squash all these commits before I merge?

**Comment by davidsavagejr** [comment]
@ChrisMissal will do.

**Pull request closed without merging**
